#!/usr/bin/env bash

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  printf "\n%b\n" "$1"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="$2"

  if [[ -w "$HOME/.zshrc.local" ]]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshenv"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if (( skip_new_line )); then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

trap 'ret=$?; test $ret -ne 0 && printf "\033[0;31mFailed to complete setup. \033[0m Please send the output of $HOME/laptop.log to team chat for help.\n\n" >&2; exit $ret' EXIT

set -e

if [[ ! -d "$HOME/.bin/" ]]; then
  mkdir "$HOME/.bin"
fi

if [[ ! -d "$HOME/.nvm/" ]]; then
  mkdir "$HOME/.nvm"
fi

if [[ ! -d "$HOME/.zsh/" ]]; then
  mkdir "$HOME/.zsh"
fi

if [[ ! -e "$HOME/.zshrc" ]] && [[ ! -L "$HOME/.zshrc" ]]; then
  touch "$HOME/.zshrc"
fi

if [[ ! -e "$HOME/.zshenv" ]] && [[ ! -L "$HOME/.zshenv" ]]; then
  touch "$HOME/.zshenv"
fi

append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

append_to_zshrc 'export HOMEBREW_CASK_OPTS="--appdir=/Applications"'

fancy_echo "\033[0;32mWelcome! Prepare to have your machine be setup for most awesome developmentness.\033[0m" 
fancy_echo "Please provide your administator password to continue."
sudo -v

if [[ ! -f $HOME/.ssh/id_rsa ]]; then
  fancy_echo "Generating SSH key..."

  eval "$(ssh-agent -s)"
  ssh-keygen -t rsa -N "" -f  $HOME/.ssh/id_rsa
fi

fancy_echo "\033[0;32mBelow is your SSH key.  Please copy it to your clipboard and associate it with your Github account before continuing. \nFor help, see: \033[0;31mhttps://help.github.com/articles/generating-ssh-keys/#step-3-add-your-ssh-key-to-your-account\033[0m"

printf "\n\033[0;32m$(cat $HOME/.ssh/id_rsa.pub)\n\n\n\033[0m"

read -p "After making sure that this key has been added to Github, press the [Enter] key to continue ..."


if [[ "$SHELL" != */zsh ]]; then
  fancy_echo "Changing your shell to zsh ..."
  chsh -s $(which zsh)

  if [[ -w "$HOME/.zshrc.local" ]]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshenv"
  fi

  source $zshrc
fi


brew_cask_install_or_upgrade(){
  if ! brew_cask_is_installed "$1"; then
    fancy_echo "Installing $1..."
    brew cask install "$@"
  fi
}

brew_cask_is_installed() {
  local name="$(brew_cask_expand_alias "$1")"

  brew cask list -1 | grep -Fqx "$name"
}

brew_cask_expand_alias() {
  brew cask info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}


brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      brew upgrade "$@"
    fi
  else
    brew install "$@"
  fi
}

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"

  brew outdated --quiet "$name" >/dev/null
  [[ $? -ne 0 ]]
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_launchctl_restart() {
  local name="$(brew_expand_alias "$1")"
  local domain="homebrew.mxcl.$name"
  local plist="$domain.plist"

  mkdir -p "$HOME/Library/LaunchAgents"
  ln -sfv "/usr/local/opt/$name/$plist" "$HOME/Library/LaunchAgents"

  if launchctl list | grep -q "$domain"; then
    launchctl unload "$HOME/Library/LaunchAgents/$plist" >/dev/null
  fi
  launchctl load "$HOME/Library/LaunchAgents/$plist" >/dev/null
}

fancy_echo "Enabling local ssh remote access ..."
  sudo systemsetup -setremotelogin on 2>&1 >/dev/null

if [[ ! $* == *--no-homebrew* ]]; then

  if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew, a good OS X package manager ..."
      ruby <(curl -fsS https://raw.githubusercontent.com/Homebrew/install/master/install)

      append_to_zshrc '# recommended by brew doctor'
      append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
      export PATH="/usr/local/bin:$PATH"
  else
    fancy_echo "Homebrew already installed. Skipping ..."
  fi

  fancy_echo "Updating Homebrew formulas ..."
  brew update

  fancy_echo "Installing MySQL, the most-used open source relational database for PHP projects ..."
    brew_install_or_upgrade 'mysql'

  fancy_echo "Installing Redis, a good key-value database ..."
    brew_install_or_upgrade 'redis'

  fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
    brew_install_or_upgrade 'the_silver_searcher'

  fancy_echo "Installing wget to download remote files ..."
    brew_install_or_upgrade 'the_silver_searcher'

  fancy_echo "Installing vim from Homebrew to get the latest version ..."
    brew_install_or_upgrade 'vim'

  fancy_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..."
    brew_install_or_upgrade 'ctags'

  fancy_echo "Installing ImageMagick, to crop and resize images ..."
    brew_install_or_upgrade 'imagemagick'

  fancy_echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
    brew_install_or_upgrade 'qt'

  fancy_echo "Installing cask, for installing desktop applications from homebrew ..."
    brew tap caskroom/cask
    brew_install_or_upgrade 'brew-cask'

  fancy_echo "Installing Vagrant, for managing local virtual machines ..."
    brew_cask_install_or_upgrade 'vagrant'

  fancy_echo "Installing Virtualbox, for hosting local virtual machines ..."
    brew_cask_install_or_upgrade 'virtualbox'

  fancy_echo "Installing Docker, a tool for managing multiple local dev environments..."
    brew_install_or_upgrade 'boot2docker'

    brew_launchctl_restart 'boot2docker'

    boot2docker init && boot2docker up
    
    brew_install_or_upgrade 'fig'
    # load boot2docker environment variables if they exist
    $(boot2docker shellinit)
    
  fancy_echo "Installing Alfred, for quick-finding applications, files and others ..."
    brew_cask_install_or_upgrade 'alfred'

  fancy_echo "Installing Hipchat, for chatty-chatting ..."
    brew_cask_install_or_upgrade 'hipchat'

  fancy_echo "Installing Box Sync, for file syncing and management ..."
    brew_cask_install_or_upgrade 'box-sync'

  node_version="0.10.33"

  fancy_echo "Installing NVM, Node.js, and NPM, for running apps and installing JavaScript packages ..."
    brew_install_or_upgrade 'nvm'

    append_to_zshrc 'export PATH="$PATH:/usr/local/lib/node_modules"'
    append_to_zshrc 'export NVM_DIR=$HOME/.nvm'
    append_to_zshrc 'source $(brew --prefix nvm)/nvm.sh' 1

    source $(brew --prefix nvm)/nvm.sh
    nvm install "$node_version"

    fancy_echo "Setting $node_version as the global default nodejs..."
    nvm alias default "$node_version"

  fancy_echo "Upgrading and linking OpenSSL ..."
    brew_install_or_upgrade 'openssl'
    brew unlink openssl && brew link openssl --force

  fancy_echo "Installing Python..."
    brew_install_or_upgrade 'python'

  fancy_echo "Installing Fabric for managing projects and environments ..."
    pip install fabric

  fancy_echo "Installing Virtualenv for handling python environments ..."
    pip install virtualenv virtualenvwrapper

  fancy_echo "Installing z, a command-line tool for quickly changing to often-used directories..."
    brew_install_or_upgrade 'z'
    append_to_zshrc 'source $(brew --prefix)/etc/profile.d/z.sh'
    touch $HOME/.z

  fancy_echo "Adding Grunt for automated build tasks ..."
    npm install -g grunt-cli

  fancy_echo "Installing Heroku CLI for managing Heroku apps and Foreman for managing app processes ..."
    brew_install_or_upgrade 'heroku-toolbelt'

  if ! command -v rcup >/dev/null; then
    fancy_echo "Installing rcm, to manage your dotfiles ..."
      brew tap thoughtbot/formulae
      brew_install_or_upgrade 'rcm'
  else
    fancy_echo "rcm already installed. Skipping ..."
  fi

fi  # --no-homebrew

fancy_echo "Installing dotfiles..."

if [[ ! -d "$HOME/.dotfiles/" ]]; then
  git clone git@github.com:rallygroup/dotfiles.git $HOME/.dotfiles
fi

if [[ ! -d "$HOME/.dotfiles/.git" ]]; then
  cd $HOME/.dotfiles; git remote add origin https://github.com/rallygroup/dotfiles.git
  git pull origin master
  cd $HOME
fi

if [[ ! -f "$HOME/.dotfiles/zsh/oh-my-zsh.sh" ]]; then
  fancy_echo "Installing oh-my-zsh, a great zsh library"
  export ZSH=$HOME/.zsh
  # skipping robbyrussell's install script until this pull request is merged https://github.com/robbyrussell/oh-my-zsh/pull/3353/commits
  curl -L https://raw.github.com/sxalexander/oh-my-zsh/master/tools/install.sh | sh
fi

env RCRC=$HOME/dotfiles/rcrc rcup

if [[ ! -f $HOME/.bin/wp ]]; then
  fancy_echo "Installing wp-cli, a WordPress command line interface..."
  
  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  chmod +x wp-cli.phar
  sudo mv wp-cli.phar $HOME/.bin/wp

fi

fancy_echo "Installing your personal additions from ~/.laptop.local ..."
  if [[ -f $HOME/.laptop.local ]]; then
    source $HOME/.laptop.local
  fi

fancy_echo "Copying SSH key to clipboard..."
cat $HOME/.ssh/id_rsa.pub | pbcopy

fancy_echo "\033[0;32mInstall complete ! \033[0m" 
fancy_echo "\033[0;32mYour public SSH key is now in your clipboard, please paste that into general chat to share with the team. \033[0m"

exec zsh -l
source $HOME/.zshrc